export type Role='ADMIN'|'SUPERVISOR'|'ADVISOR'
export interface User {id:number;username:string;email:string;first_name:string;last_name:string;full_name:string;role:Role;is_active:boolean;supervisor_id?:number|null;advisor_phone?:string;specialty?:string;profile_notes?:string}
export interface Paginated<T>{count:number;next:string|null;previous:string|null;results:T[]}
export interface Student{id:number;advisor:number;advisor_name:string;supervisor_name:string;first_name:string;last_name:string;student_code:string;phone:string;school:string;grade_year:string;field_major:string;gender:string;date_of_birth:string|null;enrollment_date:string;status:'ACTIVE'|'INACTIVE'|'ARCHIVED';notes:string;created_at:string;updated_at:string}
export interface WeeklyPerformance{id:number;student:number;week_start:string;total_study_hours:string;test_questions:number;written_questions:number;advisor_notes:string;created_at:string}
export interface AssessmentParameter{id?:number;parameter_name:string;value:string;unit_label?:string;note?:string;display_order:number}
export interface AssessmentResult{id:number;student:number;assessment_name:string;assessment_date:string;overall_score:string|null;advisor_notes:string;parameters:AssessmentParameter[];created_at:string}
export interface Challenge{id:number;student:number;title:string;category:string;description:string;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';status:'OPEN'|'IN_PROGRESS'|'RESOLVED';date_identified:string;resolution_notes:string;resolved_date:string|null;created_at:string}
export interface ReviewCategory{id:number;name:string;is_system:boolean;is_active:boolean}
export interface ReviewStatusHistory{id:number;status:ProgramReview['implementation_status'];changed_by:number;changed_by_name:string;note:string;created_at:string}
export interface ProgramReview{id:number;supervisor:number;advisor:number;advisor_name:string;student:number|null;student_name:string;review_date:string;overall_quality_rating:number;error_severity:'NONE'|'MINOR'|'MODERATE'|'MAJOR';error_categories:ReviewCategory[];problem_description:string;incorrect_logic_location:string;recommended_solution:string;implementation_status:'ISSUE_IDENTIFIED'|'SOLUTION_PROVIDED'|'AWAITING_IMPLEMENTATION'|'IMPLEMENTED'|'NOT_IMPLEMENTED';advisor_implementation_notes:string;date_implemented:string|null;supervisor_follow_up_notes:string;status_history:ReviewStatusHistory[];created_at:string}
