import {ReactNode} from 'react'

export function Spinner(){return <div className="flex min-h-40 items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-slate-800" aria-label="در حال بارگذاری"/></div>}
export function EmptyState({title='اطلاعاتی وجود ندارد.',description}:{title?:string;description?:string}){return <div className="card p-8 text-center"><div className="text-sm font-semibold text-slate-700">{title}</div>{description&&<div className="mt-2 text-sm text-slate-500">{description}</div>}</div>}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){return <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><div>{message}</div>{onRetry&&<button className="btn-secondary mt-3" onClick={onRetry}>تلاش دوباره</button>}</div>}
export function PageHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-bold text-slate-900 sm:text-2xl">{title}</h1>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{action}</div>}
export function KPICard({label,value,hint}:{label:string;value:ReactNode;hint?:string}){return <div className="card p-4"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold text-slate-900">{value}</div>{hint&&<div className="mt-1 text-xs text-slate-400">{hint}</div>}</div>}
export function Field({label,error,children}:{label:string;error?:string;children:ReactNode}){return <label className="block"><span className="label">{label}</span>{children}{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
export function Modal({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white p-4 shadow-xl sm:max-w-2xl sm:rounded-2xl sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-lg font-bold">{title}</h2><button aria-label="بستن" className="h-10 w-10 rounded-lg border border-slate-200 text-xl" onClick={onClose}>×</button></div>{children}</div></div>}
export function Badge({children,tone='slate'}:{children:ReactNode;tone?:'slate'|'green'|'amber'|'red'|'blue'}){const cls={slate:'bg-slate-100 text-slate-700',green:'bg-emerald-100 text-emerald-800',amber:'bg-amber-100 text-amber-800',red:'bg-red-100 text-red-800',blue:'bg-blue-100 text-blue-800'}[tone];return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${cls}`}>{children}</span>}
export function Pagination({count,page,pageSize=20,onPage}:{count:number;page:number;pageSize?:number;onPage:(p:number)=>void}){const pages=Math.max(1,Math.ceil(count/pageSize));if(pages<=1)return null;return <div className="mt-4 flex items-center justify-between gap-3 text-sm"><button className="btn-secondary" disabled={page<=1} onClick={()=>onPage(page-1)}>قبلی</button><span className="text-slate-500">صفحه {page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span><button className="btn-secondary" disabled={page>=pages} onClick={()=>onPage(page+1)}>بعدی</button></div>}
