import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {api} from '../api/client'
import {useAuth} from '../contexts/AuthContext'
import {KPICard,PageHeader,Spinner,ErrorState,EmptyState} from '../components/ui'
import {errorMessage,faNumber} from '../utils/format'

export default function DashboardPage(){const {user}=useAuth();const [data,setData]=useState<any>(null);const [err,setErr]=useState('')
 const load=()=>{setErr('');api.get(`/dashboard/${user?.role.toLowerCase()}/`).then(r=>setData(r.data)).catch(e=>setErr(errorMessage(e)))}
 useEffect(load,[user?.role]); if(!data&&!err)return <Spinner/>; if(err)return <ErrorState message={err} onRetry={load}/>
 const labels:any=user?.role==='ADMIN'?{users:'کل کاربران',supervisors:'ناظران فعال',advisors:'مشاوران فعال',students:'دانش‌آموزان فعال',open_challenges:'چالش‌های باز',pending_reviews:'بررسی‌های باز'}:user?.role==='SUPERVISOR'?{advisors:'مشاوران',active_students:'دانش‌آموزان فعال',students_requiring_attention:'نیازمند توجه',unresolved_program_issues:'ایرادهای حل‌نشده',implemented_recommendations:'راهکارهای اجراشده',pending_recommendations:'راهکارهای در انتظار'}:{active_students:'دانش‌آموزان فعال',updated_this_week:'به‌روزشده این هفته',missing_weekly_updates:'بدون گزارش هفتگی',open_challenges:'چالش‌های باز',pending_recommendations:'بازخوردهای در انتظار',recent_assessments:'ارزیابی‌های ۳۰ روز اخیر'}
 return <><PageHeader title="داشبورد" description="نمای کلی بر اساس اطلاعات ثبت‌شده در سامانه"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{Object.entries(data.kpis||{}).map(([k,v])=><KPICard key={k} label={labels[k]||k} value={faNumber(v as number)}/>)}</div>
 {user?.role==='SUPERVISOR'&&<div className="mt-6 grid gap-6 xl:grid-cols-2"><section><h2 className="mb-3 font-bold">دانش‌آموزان نیازمند توجه</h2>{data.attention?.length?<div className="space-y-3">{data.attention.map((x:any)=><Link key={x.id} to={`/students/${x.id}`} className="card block p-4 hover:border-slate-400"><div className="font-semibold">{x.name}</div><div className="mt-1 text-xs text-slate-500">مشاور: {x.advisor}</div><div className="mt-2 text-sm text-amber-700">{x.reasons.join('، ')}</div></Link>)}</div>:<EmptyState title="دانش‌آموز نیازمند توجه فوری شناسایی نشد."/>}</section><section><h2 className="mb-3 font-bold">نمای مشاوران</h2><div className="table-wrap"><table className="table"><thead><tr><th>مشاور</th><th>دانش‌آموز</th><th>مسائل فعال</th><th>راهکار معلق</th></tr></thead><tbody>{data.advisors?.map((a:any)=><tr key={a.id}><td><Link className="font-medium underline" to={`/reports?advisor=${a.id}`}>{a.name}</Link></td><td>{faNumber(a.students)}</td><td>{faNumber(a.active_issues)}</td><td>{faNumber(a.pending_recommendations)}</td></tr>)}</tbody></table></div></section></div>}
 {user?.role==='ADVISOR'&&<div className="mt-6"><h2 className="mb-3 font-bold">دسترسی سریع</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link className="btn-secondary" to="/students?add=1">افزودن دانش‌آموز</Link><Link className="btn-secondary" to="/weekly">ثبت عملکرد هفتگی</Link><Link className="btn-secondary" to="/assessments">ثبت نتیجه ارزیابی</Link><Link className="btn-secondary" to="/challenges">ثبت چالش</Link></div></div>}
 <section className="mt-6"><h2 className="mb-3 font-bold">فعالیت‌های اخیر</h2>{data.recent_activity?.length?<div className="card divide-y divide-slate-100">{data.recent_activity.map((a:any)=><div key={a.id} className="p-4 text-sm">{a.description}</div>)}</div>:<EmptyState title="فعالیت جدیدی ثبت نشده است."/>}</section></>}
