import {useEffect,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {api} from '../api/client'
import {useAuth} from '../contexts/AuthContext'
import {Badge,EmptyState,ErrorState,Modal,PageHeader,Pagination,Spinner} from '../components/ui'
import type {AssessmentResult,Challenge,Paginated,Student,WeeklyPerformance} from '../types'
import {errorMessage,faDate,faNumber} from '../utils/format'

type Kind='weekly'|'assessments'|'challenges'
const cfg={weekly:{title:'عملکرد هفتگی',desc:'سوابق ساعت مطالعه و تعداد سؤال‌های ثبت‌شده',endpoint:'/weekly-performance/',tab:'weekly'},assessments:{title:'نتایج ارزیابی‌ها',desc:'نتایج ارزیابی‌های روان‌شناختی انجام‌شده خارج از سامانه',endpoint:'/assessment-results/',tab:'assessments'},challenges:{title:'مشکلات و چالش‌ها',desc:'پیگیری مسائل ثبت‌شده برای دانش‌آموزان',endpoint:'/challenges/',tab:'challenges'}} as const
export default function RecordOverviewPage({kind}:{kind:Kind}){
 const {user}=useAuth();const nav=useNavigate();const [rows,setRows]=useState<any[]|null>(null);const [count,setCount]=useState(0);const [page,setPage]=useState(1);const [students,setStudents]=useState<Student[]>([]);const [open,setOpen]=useState(false);const [selected,setSelected]=useState('');const [err,setErr]=useState('');const [statusFilter,setStatusFilter]=useState('');const c=cfg[kind]
 const load=()=>{setErr('');Promise.all([api.get(c.endpoint,{params:{page,...(kind==='challenges'&&statusFilter?{status:statusFilter}:{})}}),api.get('/students/',{params:{status:'ACTIVE',page_size:100}})]).then(([r,s])=>{setRows((r.data as Paginated<any>).results);setCount((r.data as Paginated<any>).count);setStudents((s.data as Paginated<Student>).results)}).catch(e=>setErr(errorMessage(e)))}
 useEffect(load,[kind,page,statusFilter]);if(!rows&&!err)return <Spinner/>;return <><PageHeader title={c.title} description={c.desc} action={user?.role==='ADVISOR'?<button className="btn-primary" onClick={()=>setOpen(true)}>ثبت جدید</button>:undefined}/>{err&&<div className="mb-4"><ErrorState message={err} onRetry={load}/></div>}{kind==='challenges'&&<div className="mb-4 max-w-xs"><select className="input" value={statusFilter} onChange={e=>{setPage(1);setStatusFilter(e.target.value)}}><option value="">همه وضعیت‌ها</option><option value="OPEN">باز</option><option value="IN_PROGRESS">در حال پیگیری</option><option value="RESOLVED">حل‌شده</option></select></div>}{!rows?.length?<EmptyState title={kind==='assessments'?'نتیجه ارزیابی ثبت نشده است.':kind==='weekly'?'هنوز عملکرد هفتگی ثبت نشده است.':'موردی ثبت نشده است.'}/>:<div className="space-y-3">{rows.map(r=><RecordRow key={r.id} kind={kind} row={r} students={students}/>)}</div>}{count>0&&<Pagination count={count} page={page} onPage={setPage}/>}<Modal open={open} title="انتخاب دانش‌آموز" onClose={()=>setOpen(false)}><div className="space-y-4"><select className="input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">دانش‌آموز را انتخاب کنید</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.student_code}</option>)}</select><div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setOpen(false)}>انصراف</button><button className="btn-primary" disabled={!selected} onClick={()=>nav(`/students/${selected}?tab=${c.tab}&add=${kind}`)}>ادامه ثبت</button></div></div></Modal></>}
function RecordRow({kind,row,students}:{kind:Kind;row:WeeklyPerformance|AssessmentResult|Challenge;students:Student[]}){const sid=(row as any).student;const s=students.find(x=>x.id===sid);return <Link to={`/students/${sid}?tab=${cfg[kind].tab}`} className="card block p-4 hover:border-slate-400"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="font-semibold">{s?`${s.first_name} ${s.last_name}`:`دانش‌آموز #${sid}`}</div>{kind==='weekly'&&<div className="mt-2 text-sm text-slate-600">ساعت مطالعه: {faNumber((row as WeeklyPerformance).total_study_hours)} · تستی: {faNumber((row as WeeklyPerformance).test_questions)} · تشریحی: {faNumber((row as WeeklyPerformance).written_questions)}</div>}{kind==='assessments'&&<div className="mt-2 text-sm text-slate-600">{(row as AssessmentResult).assessment_name} · نمره کلی: {(row as AssessmentResult).overall_score??'—'}</div>}{kind==='challenges'&&<div className="mt-2 text-sm text-slate-600">{(row as Challenge).title} · {(row as Challenge).category}</div>}</div><div className="flex items-center gap-2">{kind==='challenges'&&<Badge tone={(row as Challenge).status==='RESOLVED'?'green':'amber'}>{(row as Challenge).status}</Badge>}<span className="text-xs text-slate-400">{faDate(kind==='weekly'?(row as WeeklyPerformance).week_start:kind==='assessments'?(row as AssessmentResult).assessment_date:(row as Challenge).date_identified)}</span></div></div></Link>}
