import {useEffect,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {api} from '../api/client'
import {useAuth} from '../contexts/AuthContext'
import {EmptyState,ErrorState,KPICard,PageHeader,Spinner} from '../components/ui'
import type {Paginated,Student,User} from '../types'
import {errorMessage,faDate,faNumber} from '../utils/format'
export default function ReportsPage(){const {user}=useAuth();const [sp]=useSearchParams();const [advisors,setAdvisors]=useState<User[]>([]);const [students,setStudents]=useState<Student[]>([]);const [advisorId,setAdvisorId]=useState(sp.get('advisor')||'');const [studentId,setStudentId]=useState('');const [advisorSummary,setAdvisorSummary]=useState<any>(null);const [studentSummary,setStudentSummary]=useState<any>(null);const [err,setErr]=useState('');const [loading,setLoading]=useState(true)
 useEffect(()=>{Promise.all([api.get('/users/',{params:{role:'ADVISOR',page_size:100}}),api.get('/students/',{params:{status:'ACTIVE',page_size:100}})]).then(([a,s])=>{setAdvisors((a.data as Paginated<User>).results);setStudents((s.data as Paginated<Student>).results)}).catch(e=>setErr(errorMessage(e))).finally(()=>setLoading(false))},[])
 useEffect(()=>{if(advisorId)api.get(`/dashboard/advisor/${advisorId}/summary/`).then(r=>setAdvisorSummary(r.data)).catch(e=>setErr(errorMessage(e)));else setAdvisorSummary(null)},[advisorId])
 useEffect(()=>{if(studentId)api.get(`/dashboard/student/${studentId}/summary/`).then(r=>setStudentSummary(r.data)).catch(e=>setErr(errorMessage(e)));else setStudentSummary(null)},[studentId])
 if(loading)return <Spinner/>;return <><PageHeader title="گزارش‌ها و خلاصه مدیریتی" description="خلاصه‌های محاسباتی فقط بر اساس داده‌های ذخیره‌شده در سامانه"/>{err&&<div className="mb-4"><ErrorState message={err}/></div>}<div className="grid gap-5 xl:grid-cols-2">{user?.role!=='ADVISOR'&&<section className="card p-5"><h2 className="font-bold">گزارش مشاور</h2><select className="input mt-4" value={advisorId} onChange={e=>setAdvisorId(e.target.value)}><option value="">مشاور را انتخاب کنید</option>{advisors.map(a=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select>{advisorSummary?<div className="mt-5 grid grid-cols-2 gap-3"><KPICard label="دانش‌آموز فعال" value={faNumber(advisorSummary.active_students)}/><KPICard label="به‌روزرسانی هفتگی" value={faNumber(advisorSummary.regularly_updated)}/><KPICard label="گزارش‌های جاافتاده" value={faNumber(advisorSummary.missing_weekly_updates)}/><KPICard label="چالش‌های باز" value={faNumber(advisorSummary.open_challenges)}/><KPICard label="ایرادهای جدی" value={faNumber(advisorSummary.major_issues)}/><KPICard label="راهکارهای معلق" value={faNumber(advisorSummary.pending_recommendations)}/></div>:<div className="mt-5"><EmptyState title="برای مشاهده گزارش، مشاور را انتخاب کنید."/></div>}</section>}<section className="card p-5"><h2 className="font-bold">گزارش دانش‌آموز</h2><select className="input mt-4" value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">دانش‌آموز را انتخاب کنید</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.student_code}</option>)}</select>{studentSummary?<div className="mt-5 space-y-3 text-sm"><Row k="آخرین هفته" v={studentSummary.latest_weekly?faDate(studentSummary.latest_weekly.week_start):'—'}/><Row k="تغییر ساعت مطالعه" v={studentSummary.changes.study_hours==null?'داده کافی نیست':`${faNumber(studentSummary.changes.study_hours)}٪`}/><Row k="تغییر سؤال تستی" v={studentSummary.changes.test_questions==null?'داده کافی نیست':`${faNumber(studentSummary.changes.test_questions)}٪`}/><Row k="تغییر سؤال تشریحی" v={studentSummary.changes.written_questions==null?'داده کافی نیست':`${faNumber(studentSummary.changes.written_questions)}٪`}/><Row k="چالش‌های باز" v={faNumber(studentSummary.open_challenges)}/><Row k="بالاترین شدت چالش" v={studentSummary.highest_severity_challenge||'—'}/><Row k="آخرین ارزیابی" v={studentSummary.latest_assessment?`${studentSummary.latest_assessment.name} · ${studentSummary.latest_assessment.overall_score??'بدون نمره کلی'}`:'—'}/><Row k="آخرین وضعیت راهکار" v={studentSummary.latest_review?.status||'—'}/><p className="pt-2 text-xs leading-6 text-slate-500">این گزارش تشخیصی نیست و تنها روندها و وضعیت‌های ثبت‌شده را خلاصه می‌کند.</p></div>:<div className="mt-5"><EmptyState title="برای مشاهده گزارش، دانش‌آموز را انتخاب کنید."/></div>}</section></div></>}
function Row({k,v}:{k:string;v:any}){return <div className="flex items-start justify-between gap-4 border-b border-slate-100 py-2"><span className="text-slate-500">{k}</span><strong className="text-left">{v}</strong></div>}
