import {FormEvent,useEffect,useState} from 'react'
import {api} from '../api/client'
import {useAuth} from '../contexts/AuthContext'
import {Badge,EmptyState,ErrorState,Field,Modal,PageHeader,Pagination,Spinner} from '../components/ui'
import type {Paginated,Role,User} from '../types'
import {errorMessage,roleLabel} from '../utils/format'

const blank=(role:Role)=>({username:'',email:'',first_name:'',last_name:'',role,password:'',supervisor_id:'',advisor_phone:'',specialty:'',profile_notes:'',is_active:true})
export default function UserListPage({fixedRole,title}:{fixedRole?:Role;title?:string}){
 const {user:me}=useAuth();const effectiveRole=(fixedRole||(me?.role==='SUPERVISOR'?'ADVISOR':'ADVISOR')) as Role
 const [data,setData]=useState<Paginated<User>|null>(null);const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState<User|null>(null);const [passwordUser,setPasswordUser]=useState<User|null>(null);const [newPassword,setNewPassword]=useState('');const [tempResult,setTempResult]=useState<{user:string;password:string}|null>(null);const [err,setErr]=useState('');const [busy,setBusy]=useState(false);const [supervisors,setSupervisors]=useState<User[]>([]);const [form,setForm]=useState<any>(blank(effectiveRole))
 const role=fixedRole||(me?.role==='SUPERVISOR'?'ADVISOR':undefined)
 const load=()=>{setErr('');api.get('/users/',{params:{page,search:search||undefined,role:role||undefined}}).then(r=>setData(r.data)).catch(e=>setErr(errorMessage(e)))}
 useEffect(()=>{load()},[page,role]); useEffect(()=>{if(me?.role==='ADMIN')api.get('/users/',{params:{role:'SUPERVISOR',page_size:100}}).then(r=>setSupervisors(r.data.results||[]))},[me?.role])
 const startAdd=()=>{setEditing(null);setForm(blank(effectiveRole));setOpen(true)}
 const startEdit=(u:User)=>{setEditing(u);setForm({username:u.username,email:u.email,first_name:u.first_name,last_name:u.last_name,role:u.role,password:'',supervisor_id:u.supervisor_id||'',advisor_phone:u.advisor_phone||'',specialty:u.specialty||'',profile_notes:u.profile_notes||'',is_active:u.is_active});setOpen(true)}
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErr('');try{const payload:any={...form};if(!payload.password)delete payload.password;if(payload.role==='ADVISOR'&&me?.role==='ADMIN'&&payload.supervisor_id)payload.supervisor_id=Number(payload.supervisor_id);else if(payload.role!=='ADVISOR'||me?.role!=='ADMIN')delete payload.supervisor_id;if(editing)await api.patch(`/users/${editing.id}/`,payload);else await api.post('/users/',payload);setOpen(false);load()}catch(e){setErr(errorMessage(e))}finally{setBusy(false)}}
 const deactivate=async(id:number)=>{if(!confirm('حساب کاربر غیرفعال شود؟'))return;try{await api.delete(`/users/${id}/`);load()}catch(e){setErr(errorMessage(e))}}
 const makeTemporary=async(u:User)=>{if(!confirm('یک رمز موقت جدید ایجاد شود؟ رمز قبلی دیگر معتبر نخواهد بود.'))return;setBusy(true);try{const r=await api.post(`/users/${u.id}/temporary-password/`);setTempResult({user:u.full_name,password:r.data.temporary_password})}catch(e){setErr(errorMessage(e))}finally{setBusy(false)}}
 const resetPassword=async(e:FormEvent)=>{e.preventDefault();if(!passwordUser)return;setBusy(true);try{await api.post(`/users/${passwordUser.id}/reset-password/`,{new_password:newPassword});setPasswordUser(null);setNewPassword('')}catch(e){setErr(errorMessage(e))}finally{setBusy(false)}}
 if(!data&&!err)return <Spinner/>
 return <><PageHeader title={title||'مدیریت کاربران'} description="ایجاد، ویرایش، غیرفعال‌سازی و مدیریت حساب‌های کاربری" action={<button className="btn-primary" onClick={startAdd}>افزودن کاربر</button>}/>{err&&<div className="mb-4"><ErrorState message={err}/></div>}<div className="mb-4 flex gap-2"><input className="input max-w-md" placeholder="جستجو نام، نام کاربری یا ایمیل" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button className="btn-secondary" onClick={()=>{setPage(1);load()}}>جستجو</button></div>{data?.results.length===0&&<EmptyState title="کاربری با این معیار پیدا نشد."/>}
 <div className="grid gap-3 md:hidden">{data?.results.map(u=><div className="card p-4" key={u.id}><div className="flex items-center justify-between gap-2"><div className="font-semibold">{u.full_name}</div><Badge tone={u.is_active?'green':'red'}>{u.is_active?'فعال':'غیرفعال'}</Badge></div><div className="mt-2 text-sm text-slate-500">{u.username} · {roleLabel(u.role)}</div><div className="mt-3 flex flex-wrap gap-3 text-sm"><button className="font-medium underline" onClick={()=>startEdit(u)}>ویرایش</button>{me?.role==='ADMIN'&&<><button className="font-medium underline" onClick={()=>setPasswordUser(u)}>تغییر رمز</button><button className="font-medium underline" onClick={()=>makeTemporary(u)}>رمز موقت</button></>}{u.id!==me?.id&&u.is_active&&<button className="text-red-600" onClick={()=>deactivate(u.id)}>غیرفعال</button>}</div></div>)}</div>
 <div className="table-wrap hidden md:block"><table className="table"><thead><tr><th>نام</th><th>نام کاربری</th><th>ایمیل</th><th>نقش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{data?.results.map(u=><tr key={u.id}><td className="whitespace-nowrap font-medium">{u.full_name}</td><td>{u.username}</td><td>{u.email}</td><td><Badge tone="blue">{roleLabel(u.role)}</Badge></td><td><Badge tone={u.is_active?'green':'red'}>{u.is_active?'فعال':'غیرفعال'}</Badge></td><td><div className="flex flex-wrap gap-3"><button className="text-sm font-medium underline" onClick={()=>startEdit(u)}>ویرایش</button>{me?.role==='ADMIN'&&<><button className="text-sm font-medium underline" onClick={()=>setPasswordUser(u)}>تغییر رمز</button><button className="text-sm font-medium underline" onClick={()=>makeTemporary(u)}>رمز موقت</button></>}{u.id!==me?.id&&u.is_active&&<button className="text-sm text-red-600" onClick={()=>deactivate(u.id)}>غیرفعال</button>}</div></td></tr>)}</tbody></table></div>{data&&<Pagination count={data.count} page={page} onPage={setPage}/>} 
 <Modal open={open} title={editing?'ویرایش حساب کاربری':'افزودن حساب کاربری'} onClose={()=>setOpen(false)}><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="نام"><input className="input" required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></Field><Field label="نام خانوادگی"><input className="input" required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></Field><Field label="نام کاربری"><input className="input" required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Field><Field label="ایمیل"><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field>{!fixedRole&&me?.role==='ADMIN'&&!editing&&<Field label="نقش"><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="SUPERVISOR">ناظر</option><option value="ADVISOR">مشاور</option><option value="ADMIN">مدیر</option></select></Field>}{form.role==='ADVISOR'&&me?.role==='ADMIN'&&<Field label="ناظر"><select className="input" required value={form.supervisor_id} onChange={e=>setForm({...form,supervisor_id:e.target.value})}><option value="">انتخاب کنید</option>{supervisors.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></Field>}{form.role==='ADVISOR'&&<><Field label="تلفن مشاور"><input className="input" value={form.advisor_phone} onChange={e=>setForm({...form,advisor_phone:e.target.value})}/></Field><Field label="تخصص/حوزه"><input className="input" value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}/></Field><div className="sm:col-span-2"><Field label="یادداشت پروفایل"><textarea className="input min-h-20" value={form.profile_notes} onChange={e=>setForm({...form,profile_notes:e.target.value})}/></Field></div></>}{!editing&&<Field label="رمز عبور"><input className="input" type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field>}{editing&&me?.role==='ADMIN'&&<Field label="وضعیت حساب"><select className="input" value={form.is_active?'1':'0'} onChange={e=>setForm({...form,is_active:e.target.value==='1'})}><option value="1">فعال</option><option value="0">غیرفعال</option></select></Field>}<div className="sm:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>انصراف</button><button className="btn-primary" disabled={busy}>{busy?'در حال ذخیره...':'ذخیره'}</button></div></form></Modal>
 <Modal open={!!passwordUser} title="تغییر رمز عبور" onClose={()=>setPasswordUser(null)}><form onSubmit={resetPassword} className="space-y-4"><p className="text-sm text-slate-600">رمز قبلی قابل مشاهده نیست. رمز جدید برای {passwordUser?.full_name} تنظیم می‌شود.</p><Field label="رمز جدید"><input className="input" type="password" minLength={8} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setPasswordUser(null)}>انصراف</button><button className="btn-primary" disabled={busy}>ثبت رمز جدید</button></div></form></Modal><Modal open={!!tempResult} title="رمز عبور موقت" onClose={()=>setTempResult(null)}>{tempResult&&<div className="space-y-4"><p className="text-sm text-slate-600">رمز موقت برای {tempResult.user} فقط در این پنجره نمایش داده می‌شود. آن را از مسیر امن تحویل دهید.</p><div dir="ltr" className="rounded-lg bg-slate-100 p-4 text-center font-mono text-lg font-bold">{tempResult.password}</div><div className="flex justify-end"><button className="btn-primary" onClick={()=>setTempResult(null)}>بستن</button></div></div>}</Modal></>}
