from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='ProgramLogicCategory',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('is_system',models.BooleanField(default=False)),('is_active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Student',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('first_name',models.CharField(max_length=80)),('last_name',models.CharField(max_length=80)),('student_code',models.CharField(db_index=True,max_length=50,unique=True)),('phone',models.CharField(blank=True,max_length=30)),('school',models.CharField(blank=True,max_length=150)),('grade_year',models.CharField(blank=True,max_length=80)),('field_major',models.CharField(blank=True,max_length=120)),('gender',models.CharField(blank=True,max_length=30)),('date_of_birth',models.DateField(blank=True,null=True)),('enrollment_date',models.DateField()),('status',models.CharField(choices=[('ACTIVE','فعال'),('INACTIVE','غیرفعال'),('ARCHIVED','بایگانی‌شده')],db_index=True,default='ACTIVE',max_length=20)),('notes',models.TextField(blank=True)),('advisor',models.ForeignKey(db_index=True,limit_choices_to={'role':'ADVISOR'},on_delete=django.db.models.deletion.PROTECT,related_name='students',to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='WeeklyPerformance',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('week_start',models.DateField(db_index=True)),('total_study_hours',models.DecimalField(decimal_places=2,max_digits=6,validators=[django.core.validators.MinValueValidator(0)])),('test_questions',models.PositiveIntegerField(default=0)),('written_questions',models.PositiveIntegerField(default=0)),('advisor_notes',models.TextField(blank=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='weekly_created',to=settings.AUTH_USER_MODEL)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='weekly_performances',to='counseling.student')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='weekly_updated',to=settings.AUTH_USER_MODEL))
        ],options={'ordering':['-week_start']},),
        migrations.AddConstraint(model_name='weeklyperformance',constraint=models.UniqueConstraint(fields=('student','week_start'),name='uniq_student_week')),
        migrations.CreateModel(name='AssessmentResult',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('assessment_name',models.CharField(db_index=True,max_length=180)),('assessment_date',models.DateField(db_index=True)),('overall_score',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('advisor_notes',models.TextField(blank=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='assessment_created',to=settings.AUTH_USER_MODEL)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assessment_results',to='counseling.student')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='assessment_updated',to=settings.AUTH_USER_MODEL))
        ],options={'ordering':['-assessment_date','-created_at']}),
        migrations.CreateModel(name='AssessmentResultParameter',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('parameter_name',models.CharField(max_length=160)),('value',models.DecimalField(decimal_places=3,max_digits=12)),('unit_label',models.CharField(blank=True,max_length=40)),('note',models.CharField(blank=True,max_length=300)),('display_order',models.PositiveIntegerField(default=0)),('assessment_result',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='parameters',to='counseling.assessmentresult'))
        ],options={'ordering':['display_order','id']}),
        migrations.CreateModel(name='StudentChallenge',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180)),('category',models.CharField(db_index=True,max_length=120)),('description',models.TextField()),('severity',models.CharField(choices=[('LOW','کم'),('MEDIUM','متوسط'),('HIGH','زیاد'),('CRITICAL','بحرانی')],db_index=True,default='MEDIUM',max_length=20)),('status',models.CharField(choices=[('OPEN','باز'),('IN_PROGRESS','در حال پیگیری'),('RESOLVED','حل‌شده')],db_index=True,default='OPEN',max_length=20)),('date_identified',models.DateField(db_index=True)),('resolution_notes',models.TextField(blank=True)),('resolved_date',models.DateField(blank=True,null=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='challenge_created',to=settings.AUTH_USER_MODEL)),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='challenges',to='counseling.student')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='challenge_updated',to=settings.AUTH_USER_MODEL))
        ],options={'ordering':['-date_identified','-created_at']}),
        migrations.CreateModel(name='ProgramLogicReview',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('review_date',models.DateField(db_index=True)),('overall_quality_rating',models.PositiveSmallIntegerField(choices=[(1,'بسیار ضعیف'),(2,'ضعیف'),(3,'قابل قبول'),(4,'خوب'),(5,'عالی')])),('error_severity',models.CharField(choices=[('NONE','بدون ایراد'),('MINOR','جزئی'),('MODERATE','متوسط'),('MAJOR','جدی')],db_index=True,default='NONE',max_length=20)),('problem_description',models.TextField(blank=True)),('incorrect_logic_location',models.TextField(blank=True)),('recommended_solution',models.TextField(blank=True)),('implementation_status',models.CharField(choices=[('ISSUE_IDENTIFIED','ایراد ثبت شده'),('SOLUTION_PROVIDED','راهکار ارائه شده'),('AWAITING_IMPLEMENTATION','در انتظار اجرا'),('IMPLEMENTED','اجرا شده'),('NOT_IMPLEMENTED','اجرا نشده')],db_index=True,default='ISSUE_IDENTIFIED',max_length=40)),('advisor_implementation_notes',models.TextField(blank=True)),('date_implemented',models.DateField(blank=True,null=True)),('supervisor_follow_up_notes',models.TextField(blank=True)),('advisor',models.ForeignKey(limit_choices_to={'role':'ADVISOR'},on_delete=django.db.models.deletion.PROTECT,related_name='program_reviews_received',to=settings.AUTH_USER_MODEL)),('error_categories',models.ManyToManyField(blank=True,related_name='reviews',to='counseling.programlogiccategory')),('student',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='program_reviews',to='counseling.student')),('supervisor',models.ForeignKey(limit_choices_to={'role':'SUPERVISOR'},on_delete=django.db.models.deletion.PROTECT,related_name='program_reviews_created',to=settings.AUTH_USER_MODEL))
        ],options={'ordering':['-review_date','-created_at']}),
        migrations.CreateModel(name='Activity',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('activity_type',models.CharField(choices=[('STUDENT_ADDED','دانش‌آموز افزوده شد'),('WEEKLY_CREATED','عملکرد هفتگی ثبت شد'),('ASSESSMENT_CREATED','نتیجه ارزیابی ثبت شد'),('CHALLENGE_OPENED','چالش ثبت شد'),('CHALLENGE_RESOLVED','چالش حل شد'),('REVIEW_CREATED','بررسی ناظر ثبت شد'),('RECOMMENDATION_IMPLEMENTED','راهکار اجرا شد')],db_index=True,max_length=50)),('description',models.CharField(max_length=300)),('actor',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='activities',to=settings.AUTH_USER_MODEL)),('advisor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='advisor_activities',to=settings.AUTH_USER_MODEL)),('student',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='activities',to='counseling.student'))
        ],options={'ordering':['-created_at']}),
    ]
